version: "3"
services:
  api-express:
    build:
      dockerfile: Dockerfile.dev
      context: ./socket.io
    volumes:
      - /app/node_modules
      - ./socket.io:/app

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
